language: php

php:
- '7.2'

#services:
#- mysql

#addons:
#  apt:
#    sources:
#    - mysql-5.7-trusty
#    packages:
#    - mysql-server
#    - mysql-client

#dist: trusty

#sudo: required

# Cache composer bits
cache:
  directories:
  - node_modules
  - vendor

#before_install:
#- sudo mysql_upgrade
#- sudo service mysql restart
#- mysql --version
#- mysql -e 'CREATE DATABASE roka_test;'
#- composer self-update

install:
- composer install --no-interaction

before_script:
#- cp .travis/.travis.env .env
#- pear install pear/PHP_CodeSniffer
#- phpenv rehash
- nvm install 9.11.1
- npm install -g yarn
# - yarn global add eslint@4.19.1 eslint-plugin-import@2.12.0 eslint-plugin-vue@4.5.0 eslint-config-airbnb-base@12.1.0 babel-eslint@8.2.5
# - yarn global add stylelint@9.2.1
#- yarn global add backstopjs
- yarn
- cp .travis/_settings.config.scss resources/sass/settings/_settings.config.scss

script:
- yarn lint
- yarn run production # Webpack Compilation
#- php artisan serve --host "127.0.0.1" --port "8080" &
#- yarn pu --verbose # PHPUnit
# Temporarily removed for now until we can work out how to work this
#  - backstop test --config=".travis/backstop.json"

notifications:
  slack:
    rooms:
      secure: ZP4DK7aLkl4z/fWLVvPSGzcMsXxnXx043hn8FdL6MfDfB83Bh2NHEtbn4DcdDMyCdr14ki6qp56lq95W3pM+PIjw2xxC+pLvA6+Vb5DrZXuvUqAqDhHimP7lXm9nHtQLO6nXZgDDPo1SceEQ9DgImYO04M2cLB9cLk+QrwzRYc4lVKEyTSk4jqxxz+Pd4acghw6TniFTzg4u5Dfhyj+XAD8Sn64iZ8/Eqi2uddyG5h4op5VMnQK7jlJAWPLju1pTy/bzH2jdgVC/teRfrwDz9IH6wWJKpadk1fsjEShheC6kzdKfhFnbDeLI2gClA3v50MscG132z3ouueGDURWyRQR0jH/KAAlz3a4EnNIGiSedKia+1SHoQ22pak4C2GV8ESYBJKhsxK/OoPqtXBwovwyzFnIDXenBQSKms/ko21Qj+D5OSJXBQGo1o+9sGG0aVXhb1j/p9gI954xzUPoqKQBg3mmmd9oSYanoJBGbirNbkEZO5qRI6yEiEyySw3ZzsXGTyhssDAodxwZIVy2neOD+OQCS9D5OC3mnKglI7RV1Aa2nZW99d09/8abH1bJ5bZV+ePMO9f1zj8qQY7H1Wuv9OQtNU2eqcSLpYjKceEYJwwvooFuH11SiWMZMG0m9b6lm4G1Jd4IRty6EB9pSw0sQa0hM3D7jGCpUrXshaHE=
    on_success: never
    on_fail: always
  email: false
