export default {
    ANALYTICS_SET_CAN_TRACK: 'ANALYTICS_SET_CAN_TRACK',

    RESIZE_UPDATE_DEBOUNCED: 'RESIZE_UPDATE_DEBOUNCED',
    RESIZE_UPDATE_LAZY_DEBOUNCED: 'RESIZE_UPDATE_LAZY_DEBOUNCED',

    SCROLL_UPDATE_THROTTLED: 'SCROLL_UPDATE_THROTTLED',
    SCROLL_UPDATE_LAZY_THROTTLED: 'SCROLL_UPDATE_LAZY_THROTTLED',
    SCROLL_UPDATE_DEBOUNCED: 'SCROLL_UPDATE_DEBOUNCED',
    SCROLL_UPDATE_LAZY_DEBOUNCED: 'SCROLL_UPDATE_LAZY_DEBOUNCED',
};
